In [1]:
import pandas as pd

beneficiary2008 = pd.read_csv(
    "../data/raw/beneficiary/176613_DE1_0_2008_Beneficiary_Summary_File_Sample_14/DE1_0_2008_Beneficiary_Summary_File_Sample_14.csv"
)

beneficiary2009 = pd.read_csv(
    "../data/raw/beneficiary/176584_DE1_0_2009_Beneficiary_Summary_File_Sample_14/DE1_0_2009_Beneficiary_Summary_File_Sample_14.csv"
)

beneficiary2010 = pd.read_csv(
    "../data/raw/beneficiary/176598_DE1_0_2010_Beneficiary_Summary_File_Sample_14/DE1_0_2010_Beneficiary_Summary_File_Sample_14.csv"
)

beneficiary = pd.concat([beneficiary2008, beneficiary2009, beneficiary2010], ignore_index=True)

inpatient = pd.read_csv(
    "../data/raw/inpatient//176533_DE1_0_2008_to_2010_Inpatient_Claims_Sample_14/DE1_0_2008_to_2010_Inpatient_Claims_Sample_14.csv"
)

In [2]:
print(beneficiary.columns)
beneficiary.head()

Index(['DESYNPUF_ID', 'BENE_BIRTH_DT', 'BENE_DEATH_DT', 'BENE_SEX_IDENT_CD',
       'BENE_RACE_CD', 'BENE_ESRD_IND', 'SP_STATE_CODE', 'BENE_COUNTY_CD',
       'BENE_HI_CVRAGE_TOT_MONS', 'BENE_SMI_CVRAGE_TOT_MONS',
       'BENE_HMO_CVRAGE_TOT_MONS', 'PLAN_CVRG_MOS_NUM', 'SP_ALZHDMTA',
       'SP_CHF', 'SP_CHRNKIDN', 'SP_CNCR', 'SP_COPD', 'SP_DEPRESSN',
       'SP_DIABETES', 'SP_ISCHMCHT', 'SP_OSTEOPRS', 'SP_RA_OA', 'SP_STRKETIA',
       'MEDREIMB_IP', 'BENRES_IP', 'PPPYMT_IP', 'MEDREIMB_OP', 'BENRES_OP',
       'PPPYMT_OP', 'MEDREIMB_CAR', 'BENRES_CAR', 'PPPYMT_CAR'],
      dtype='object')

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,0001448457F2ED81,19750401,NaN,2,2,0,15,150,12,12,...,2,21000.0,4096.0,0.0,670.0,430.0,0.0,2070.0,450.0,70.0
1,000188A3402777A5,19220401,NaN,2,5,0,31,270,12,12,...,2,0.0,0.0,0.0,2100.0,890.0,0.0,2330.0,690.0,30.0
2,0001A1CB9A542107,19220201,NaN,2,1,0,45,610,12,12,...,2,0.0,0.0,0.0,4890.0,1460.0,0.0,1060.0,290.0,300.0
3,0001EB1229306825,19540501,NaN,1,3,0,22,90,12,12,...,2,0.0,0.0,0.0,660.0,410.0,0.0,4470.0,1220.0,20.0
4,000238CD55A321A2,19110501,NaN,2,1,0,19,350,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,750.0,180.0,0.0

In [3]:
print(inpatient.columns)
inpatient.head()

Index(['DESYNPUF_ID', 'CLM_ID', 'SEGMENT', 'CLM_FROM_DT', 'CLM_THRU_DT',
       'PRVDR_NUM', 'CLM_PMT_AMT', 'NCH_PRMRY_PYR_CLM_PD_AMT', 'AT_PHYSN_NPI',
       'OP_PHYSN_NPI', 'OT_PHYSN_NPI', 'CLM_ADMSN_DT', 'ADMTNG_ICD9_DGNS_CD',
       'CLM_PASS_THRU_PER_DIEM_AMT', 'NCH_BENE_IP_DDCTBL_AMT',
       'NCH_BENE_PTA_COINSRNC_LBLTY_AM', 'NCH_BENE_BLOOD_DDCTBL_LBLTY_AM',
       'CLM_UTLZTN_DAY_CNT', 'NCH_BENE_DSCHRG_DT', 'CLM_DRG_CD',
       'ICD9_DGNS_CD_1', 'ICD9_DGNS_CD_2', 'ICD9_DGNS_CD_3', 'ICD9_DGNS_CD_4',
       'ICD9_DGNS_CD_5', 'ICD9_DGNS_CD_6', 'ICD9_DGNS_CD_7', 'ICD9_DGNS_CD_8',
       'ICD9_DGNS_CD_9', 'ICD9_DGNS_CD_10', 'ICD9_PRCDR_CD_1',
       'ICD9_PRCDR_CD_2', 'ICD9_PRCDR_CD_3', 'ICD9_PRCDR_CD_4',
       'ICD9_PRCDR_CD_5', 'ICD9_PRCDR_CD_6', 'HCPCS_CD_1', 'HCPCS_CD_2',
       'HCPCS_CD_3', 'HCPCS_CD_4', 'HCPCS_CD_5', 'HCPCS_CD_6', 'HCPCS_CD_7',
       'HCPCS_CD_8', 'HCPCS_CD_9', 'HCPCS_CD_10', 'HCPCS_CD_11', 'HCPCS_CD_12',
       'HCPCS_CD_13', 'HCPCS_CD_14', 'HCPCS_CD_15', 'HCPCS_CD_16',
       'HCPCS_CD_17', 'HCPCS_CD_18', 'HCPCS_CD_19', 'HCPCS_CD_20',
       'HCPCS_CD_21', 'HCPCS_CD_22', 'HCPCS_CD_23', 'HCPCS_CD_24',
       'HCPCS_CD_25', 'HCPCS_CD_26', 'HCPCS_CD_27', 'HCPCS_CD_28',
       'HCPCS_CD_29', 'HCPCS_CD_30', 'HCPCS_CD_31', 'HCPCS_CD_32',
       'HCPCS_CD_33', 'HCPCS_CD_34', 'HCPCS_CD_35', 'HCPCS_CD_36',
       'HCPCS_CD_37', 'HCPCS_CD_38', 'HCPCS_CD_39', 'HCPCS_CD_40',
       'HCPCS_CD_41', 'HCPCS_CD_42', 'HCPCS_CD_43', 'HCPCS_CD_44',
       'HCPCS_CD_45'],
      dtype='object')

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,0001448457F2ED81,241351127032355,1,20080327.0,20080328.0,15016R,4000.0,0.0,9.155268e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0001448457F2ED81,241181127013424,1,20080527.0,20080608.0,1501GA,6000.0,0.0,5.435740e+08,5.435740e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0001448457F2ED81,241331127045248,1,20080723.0,20080726.0,1513QQ,8000.0,0.0,1.381846e+09,1.381846e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0001448457F2ED81,241601127014278,1,20081027.0,20081031.0,1513QQ,3000.0,0.0,1.381846e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,000188A3402777A5,241701127028305,1,20090106.0,20090110.0,3902VH,5000.0,0.0,8.657400e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
datasets = [beneficiary, inpatient]

for dataset in datasets:
    dt_columns = [col for col in dataset.columns if col.endswith('_DT')]
    for col in dt_columns:
        dataset[col] = pd.to_datetime(dataset[col], errors='coerce')

In [5]:
beneficiary["BENE_SEX_IDENT_CD"].value_counts()

BENE_SEX_IDENT_CD
2    191655
1    152142
Name: count, dtype: int64

In [ ]:
inpatient.groupby("DESYNPUF_ID").size()

DESYNPUF_ID
0001448457F2ED81    4
000188A3402777A5    3
0001EB1229306825    1
0004D74110AB2B02    2
0004E92FDA74EC8D    6
                   ..
FFFC6DF59E95B497    1
FFFDCC32BA6BD301    1
FFFE1D81055C3623    1
FFFF995283D76A08    2
FFFFD21164D5316F    1
Length: 37778, dtype: int64

In [12]:
inpatient["ICD9_DGNS_CD_1"].value_counts().head(10)

ICD9_DGNS_CD_1
486      2516
V5789    1801
41401    1689
0389     1659
49121    1596
4280     1497
5990     1461
42731    1242
41071    1171
5849     1137
Name: count, dtype: int64

In [16]:
beneficiary.to_csv(
    "../data/processed/beneficiary.csv",
    index=False
)

inpatient.to_csv(
    "../data/processed/inpatient.csv",
    index=False
)